const ADD_COUNT = "ADD_COUNT";
const SUBS_COUNT = "SUBS_COUNT";

const Todo_Request="Todo_Request";
const Todo_Success = "Todo_Success";
const Todo_Failure = "Todo_Failure";

const ADD_TODO = 'ADD_TODO';
const ADD_REQUEST = 'ADD_REQUEST';
const ADD_FAIL = 'ADD_FAIL';

const TASK_SUCCESS='TASK_SUCCESS';
const TASK_REQUEST = 'TASK_REQUEST';
const TASK_FAILURE = 'TASK_FAILURE';

const TOGGLE_SUCCESS='TOGGLE_SUCCESS';
const TOGGLE_REQUEST = 'TOGGLE_REQUEST';
const TOGGLE_FAILURE = 'TOGGLE_FAILURE';

const EDIT_SUCCESS='EDIT_SUCCESS';
const EDIT_REQUEST = 'EDIT_REQUEST';
const EDIT_FAILURE = 'EDIT_FAILURE';

const REMOVE_SUCCESS='REMOVE_SUCCESS';
const REMOVE_REQUEST = 'REMOVE_REQUEST';

export {ADD_COUNT,SUBS_COUNT,Todo_Failure,Todo_Request,
    Todo_Success,ADD_FAIL,ADD_REQUEST,ADD_TODO,
    TASK_FAILURE,TASK_REQUEST,TASK_SUCCESS,
    TOGGLE_FAILURE,TOGGLE_REQUEST,TOGGLE_SUCCESS,
    EDIT_FAILURE,EDIT_REQUEST,EDIT_SUCCESS,REMOVE_REQUEST,
    REMOVE_SUCCESS}